export const enum EventType {
  MESSAGE = 'MESSAGE',

  ERROR = 'ERROR',

  PAYMENT = 'PAYMENT',

  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',

  LOGIN = 'LOGIN',

  CREATE_COURSE = 'CREATE_COURSE',

  PARTICIPANT = 'PARTICIPANT',

  REGISTERED = 'REGISTERED',
}
