export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  CONTROLLER = 'ROLE_CONTROLLER',
  ACCOUNTANT = 'ROLE_ACCOUNTANT',
  DIRECTOR = 'ROLE_DIRECTOR',
  MANAGER = 'ROLE_MANAGER',
  TEACHER = 'ROLE_TEACHER',
  SECRETARY = 'ROLE_SECRETARY',
}
